### ISSUE TITLE
Provide example/test case for multiple orders?

### ISSUE THREAD

**Issue by zilveer** [hydra-network/exchange-core#2]
Hi,
Would you mind to provide test case/example for multiplex orders in buyOrderbook or sellOrderbook ?

Let's say that we have multiple sell orders with small quantity and different prices and a buy order with big quantity and price which is higher then the MAX(price of sell). 

Would be nice to see such example /test case.
Regards

**Comment by pistol88** [comment]
This is a higher level of APP. Anyway, describing of a best practice isn't a bad idea. I'll do it.

Usually each running of Matcher is processed in a queue, consist of order's ID\Objects:

11
12
13
14

Every "tick" launches the Matcher. We have to get a two top orders from orderbooks of market (sorted by price) and send it to Matcher:

```
$matcher = new Matcher($topBuyOrder, $topSellOrder);
$deal = $matcher->matching();
```

**Comment by zilveer** [comment]
Thx and sorry for late reply.

Regards
